### PR TITLE
Bump WordPress "tested up to" version 6.6 

### LINKED ISSUE #174: The plugin hasn't been tested with an upcoming version of WordPress
There is an upcoming WordPress version in the **release candidate** stage that the plugin hasn't been tested with. Please test it and then change the "Tested up to" field in the plugin readme.

**Tested up to:** 6.5
**Upcoming version:** 6.6

This issue will be closed automatically when the versions match.

### PR DESCRIPTION
**Pull request by ankitguptaindia**
### Description of the Change
This PR bumps the WP tested up to version 6.6, and bumps the WP min to 6.4. 

Closes https://github.com/10up/insecure-content-warning/issues/174

### Changelog Entry

> Changed - Bump WordPress "tested up to" version 6.6.
> Changed - Bump WordPress minimum from 6.3 to 6.4.

### Credits

Props @ankitguptaindia 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by dkotter — CHANGES_REQUESTED** [review]
We'll need to bump our minimum WordPress version in our E2E tests as well. Those are failing right now because it's using WordPress 6.3 and the plugin can't be installed there anymore: https://github.com/10up/insecure-content-warning/blob/develop/.github/workflows/cypress.yml#L47

**Comment by jeffpaul** [comment]
Still seeing e2e test failures, guessing that's another wp-env / dependency update that's needed?

**Comment by ankitguptaindia** [comment]
Hello @dkotter I updated WP Min version and wp-env version but tests are still failing here. COuld you check or suggest changes here? thank you!

**Comment by dkotter** [comment]
> Hello @dkotter I updated WP Min version and wp-env version but tests are still failing here. COuld you check or suggest changes here? thank you!

This seems to be the same issue Dharmesh mentions here: https://github.com/10up/insecure-content-warning/pull/172#pullrequestreview-2149967771. So this looks good to me

**Review by dkotter — APPROVED** [review]

**Pull request merged**
