### PR TITLE
fix/53: check content for Ctrl+S and Command+S

### LINKED ISSUE #53: Insecure warnings are not displaying when I used `CMD+S` shortcut
**Is your enhancement related to a problem? Please describe.**
We currently listen for direct clicks on the publish button to know when to run our checks. This means the shortcut will never fire anything from us. We would either need to add this or refactor our save listener to be more inline with how Gutenberg works (like listening for `isSavingPost`)

**Additional links**

Link to the thread can be found [here](https://tenup.teamwork.com/#/tasks/18929523?c=9024774).

### PR DESCRIPTION
**Pull request by Sidsector9**
Closes #53 

### Description of the Change

This PR enables the checks when saving through the `primary + S` shortcut.

### Benefits

This benefits the user from not saving insecure post content to the DB using the shortcut.

### Verification Process

1. In the fix branch, add an image to the editor on an HTTPS site.
2. Edit the image as HTML and replace the protocol to HTTP.
3. Try saving the post using the **Publish** or **Update** button.
4. Observe the error notice saving **1 insecure element found.**
5. Repeat steps 1 and 2 and try saving the post using `primary + S` and repeat step 4.
6. In develop branch, `primary + S` will save the post with insecure element.

### Credits

@Sidsector9 @dinhtungdu @jeffpaul @faisal-alvi 

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

Fix: Issue with saving post with insecure element using the `primary + S` shortcut.

### CODE REVIEW

**Review by dinhtungdu — CHANGES_REQUESTED** [review]
@Sidsector9, thanks for the PR! I have an issue testing this one. The warning appears when I hit `Ctrl-S` but the content is still saved. We want to prevent post saving in this case too.

**Comment by Sidsector9** [comment]
## Update
Raised an issue with the Gutenberg team - https://github.com/WordPress/gutenberg/issues/34864

**Comment by jeffpaul** [comment]
Upstream Gutenberg issue is resolved, what else is blocking progress on this @Sidsector9?

**Comment by Sidsector9** [comment]
@jeffpaul I've tried running with the [upstream fix](https://github.com/WordPress/gutenberg/pull/35361) and that didn't work either and the reason is the sequence in which event listeners are registered.

Gutenberg's listener for keypress Ctrl + S and Cmd + S runs before our logic to block post saving.
I tried to modify my code with the traditional `document.onkeydown` but that failed as well as the listener was registered at a much later point after Gutenberg finished registering all its listeners.

**Comment by jeffpaul** [comment]
@Sidsector9 @dinhtungdu any ideas then on how to resolve this issue within the plugin?

**Comment by jeffpaul** [comment]
@Sidsector9 is this PR worth keeping open to try and resolve the linked issue or are we blocked by upstream compatibility in Gutenberg?

**Comment by Sidsector9** [comment]
@jeffpaul we are blocked by upstream incompatibility with Gutenberg. It's been a while since I've looked into this, I'll spend a little more time on it this week and see what can be done about this PR.

**Comment by jeffpaul** [comment]
@Sidsector9 is there anything that could be done here or in Gutenberg to resolve this?  If not, let's go ahead and close this out if we're not realistically going to be able to impact change on this issue (and can probably then close the related issue as wontfix).

**Comment by Sidsector9** [comment]
@jeffpaul before closing this, I would like to request @fabiankaegy to weigh in his thoughts on this issue, in case he may have a solution?

**Review by faisal-alvi — COMMENTED** [review]
@Sidsector9 a big thanks for your outstanding efforts on this PR.

I tested it on an M1 Mac Air with the Chrome browser, and the behavior was as expected. When I pressed Cmd+S, the warning appeared, preventing the post from being saved. Upon resolving the warning, the post saved successfully.

image

However, I noticed a number of changes that don't appear directly related to the fix, making the code review somewhat unclear.

Also, it seems the "E2E test / WP trunk" action check [failed](https://github.com/10up/insecure-content-warning/actions/runs/5801081288/job/15724592750?pr=56). Could you please take a look?

**Comment by Sidsector9** [comment]
@faisal-alvi thanks for reviewing. I will look into the failing tests, we're facing similar failures in other repos as well.

> However, I noticed a number of changes that don't appear directly related to the fix, making the code review somewhat unclear.

I wasn't able to run linters before these changes due to incompatibilities between the NPM dependencies. Upon investigating I saw this repo had a large number of old and unused dependencies. In commit [1694ff0](https://github.com/10up/insecure-content-warning/pull/56/commits/1694ff053675b637aebe591fa02248f0fb5fb21a), I cleaned up the project so that it's aligned with the other projects we have.

If you want to focus on reviewing just the feature, then this is the commit - https://github.com/10up/insecure-content-warning/pull/56/commits/4a4d3ab2f1fa2fbcc6ed5a15f60ae4ac01d3ef02

**Review by faisal-alvi — APPROVED** [review]
@Sidsector9 Thanks for the info, makes sense, approving.

**Pull request merged**
