### PR TITLE
upkeep/78: bump min WP and PHP versions

### LINKED ISSUE #78: Bump WordPress and PHP minimums
Bump WP & PHP Minimums to the following
 
- [ ] WordPress to 5.7
- [ ] PHP to 7.4
- [ ] Remove any no-longer-needed conditional code for older version support.
- [ ] Take a look at adjusting our testing matrices, if applicable.
- [ ] Bump the minimums in plugin documentation and header fields.

### PR DESCRIPTION
**Pull request by Sidsector9**
### Description of the Change

Closes #78

### Changelog Entry

> Changed - Bump minimum PHP version from 7.0 to 7.4
> Changed - Bump minimum WordPress version from 5.3 to 5.7

### Credits

Props @vikrampm1 @Sidsector9 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by iamdharmesh — CHANGES_REQUESTED** [review]
Thanks for the PR @Sidsector9, PR changes looks good to me. However, 1-2 minor changes are required before getting this merged.

- Update versions in technical notes of readme.txt - https://github.com/10up/insecure-content-warning/blob/develop/readme.txt#L21-L22
- Node version in package.json - https://github.com/10up/insecure-content-warning/blob/develop/package.json#L82

Thanks

**Comment by Sidsector9** [comment]
@iamdharmesh as discussed on call, let's keep the node version on 12 as the dependencies are very old.

**Review by iamdharmesh — APPROVED** [review]
Thanks for the changes @jeffpaul @Sidsector9. LGTM 🚀

_@Sidsector9 I rollbacked node version to v12 as discussed_

**Comment by jeffpaul** [comment]
Linting issues appear to be preexisting so going to merge this in and we can sort out the linting concerns separately.

**Pull request merged**
